[project]
name = "mcp-client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.12.14",
    "fastapi>=0.116.1",
    "fastmcp>=2.10.6",
    "google-generativeai>=0.8.5",
    "python-dotenv>=1.1.1",
]
