[project]
name = "mcp-server-leaving"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncio>=3.4.3",
    "fastapi>=0.116.1",
    "mcp[cli]>=1.12.0",
    "uvicorn>=0.35.0",
]
